theme: jekyll-theme-minimal
# title: "[Your Name]"
description: "Portfolio | Research | Publications"
logo: /assets/profile.jpg
show_downloads: false

sass:
  style: compressed

# Navigation menu
header_pages:
  - index.md
  - cv.md
  - publications.md
  - projects.md
  - contact.md
