title: "[Your Name]"
description: "Researcher | Data Scientist | Educator"
url: "https://your-username.github.io"
baseurl: "" 
remote_theme: alshedivat/al-folio

author:
  name: "[Your Name]"
  avatar: "assets/img/profile.jpg"
  email: your.email@example.com
  linkedin: your-linkedin
  github: your-username
  scholar: your-scholar-link
  cv: "assets/pdf/CV.pdf"

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
